(part "B5817W-TP"
    (packageRef "SOD3716X135N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "833-B5817W-TP")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Micro-Commercial-Components-MCC/B5817W-TP?qs=6viq6gG%252BWEv8BqnTXWtCWg%3D%3D")
    (property "Manufacturer_Name" "MCC")
    (property "Manufacturer_Part_Number" "B5817W-TP")
    (property "Description" "Diode 20 V 1A Surface Mount SOD-123")
    (property "Datasheet_Link" "https://www.mccsemi.com/pdf/Products/B5817W-B5819W(SOD-123).pdf")
    (property "symbolName1" "B5817W-TP")
)
